name: test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test-jvm:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0
    - uses: coursier/cache-action@v6
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 21
    - name: Get submodule status hash
      id: get-submodules
      run: echo "submodules=$(git submodule status | sha256sum | awk '{print $1}')" >> $GITHUB_OUTPUT
    - uses: actions/cache@v3
      with:
        path: |
          ./dependencies/**/target
        key: ${{ runner.os }}-${{ steps.get-submodules.outputs.submodules }}-scala-native-only
    - name: Build dependencies
      run: ./dependencies/publish-deps.sh --scala-native-only
    - name: Test
      run: sbt rootJVM/test
  test-native:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0
    - uses: coursier/cache-action@v6
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 19
    - name: Get submodule status hash
      id: get-submodules
      run: echo "submodules=$(git submodule status | sha256sum | awk '{print $1}')" >> $GITHUB_OUTPUT
    - uses: actions/cache@v3
      with:
        path: |
          ./dependencies/**/target
        key: ${{ runner.os }}-${{ steps.get-submodules.outputs.submodules }}
    - name: Build dependencies
      run: ./dependencies/publish-deps.sh
    - name: Install scala-native dependencies
      run: sudo apt-get install clang libstdc++-12-dev libgc-dev
    - name: Test
      run: sbt rootNative/test
